# Generated by Django 3.1.6 on 2021-06-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CvMaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='own name')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('zender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('SheMale', 'SheMale')], max_length=7)),
                ('cv_picture', models.ImageField(upload_to='picture')),
                ('website', models.URLField(blank=True)),
                ('present_address', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('ssc_start_date', models.DateField()),
                ('ssc_start_end', models.DateField()),
                ('ssc_subject', models.CharField(choices=[('Science', 'Science'), ('Business', 'Business'), ('Humanities', 'Humanities')], max_length=20)),
                ('school_name', models.CharField(max_length=250)),
                ('hsc_start_date', models.DateField()),
                ('hsc_start_end', models.DateField()),
                ('hsc_subject', models.CharField(choices=[('Science', 'Science'), ('Business', 'Business'), ('Humanities', 'Humanities')], max_length=20)),
                ('college_name', models.CharField(max_length=250)),
                ('first_job', models.CharField(blank=True, max_length=250)),
                ('first_job_title', models.CharField(blank=True, max_length=250)),
                ('first_job_date', models.CharField(blank=True, max_length=10)),
                ('present_job', models.CharField(blank=True, max_length=250)),
                ('present_job_title', models.CharField(blank=True, max_length=250)),
                ('present_job_date', models.DateField(blank=True)),
                ('skils_title_1', models.CharField(blank=True, max_length=20)),
                ('skills_percentage_1', models.IntegerField(blank=True)),
                ('skils_title_2', models.CharField(blank=True, max_length=20)),
                ('skills_percentage_2', models.IntegerField(blank=True)),
                ('skils_title_3', models.CharField(blank=True, max_length=20)),
                ('skills_percentage_3', models.IntegerField(blank=True)),
                ('skils_title_4', models.CharField(blank=True, max_length=20)),
                ('skills_percentage_4', models.IntegerField(blank=True)),
                ('skils_title_5', models.CharField(blank=True, max_length=20)),
                ('skills_percentage_5', models.IntegerField(blank=True)),
                ('facebook', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('linkdin', models.URLField(blank=True)),
                ('youtube', models.URLField(blank=True)),
            ],
        ),
    ]
