# Generated by Django 3.1.6 on 2021-06-10 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cv_Maker_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cvmaker',
            old_name='ssc_start_date',
            new_name='school_start_date',
        ),
        migrations.RenameField(
            model_name='cvmaker',
            old_name='ssc_start_end',
            new_name='school_start_end',
        ),
    ]
