# Generated by Django 3.1.6 on 2021-06-12 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cv_Maker_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmaker',
            name='cv_picture',
            field=models.ImageField(upload_to='picture', verbose_name='Upload Course Picture'),
        ),
    ]
