# Generated by Django 3.1.5 on 2021-06-12 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Cv_Maker_App', '0002_auto_20210612_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmaker',
            name='cv_picture',
            field=models.ImageField(upload_to='picture', verbose_name='Upload CV Picture'),
        ),
        migrations.CreateModel(
            name='PracticeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, verbose_name='own name')),
                ('picture', models.ImageField(upload_to='picture', verbose_name='Upload CV Picture')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
