# Generated by Django 3.1.6 on 2021-06-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cv_Maker_App', '0002_auto_20210610_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvmaker',
            name='first_job_date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='cvmaker',
            name='present_job_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
