# Generated by Django 3.1.5 on 2021-06-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cv_Maker_App', '0004_auto_20210612_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practicemodel',
            name='picture',
            field=models.FileField(upload_to='pictures', verbose_name='Upload CV Picture'),
        ),
    ]
