# Generated by Django 3.1.5 on 2021-06-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cv_Maker_App', '0008_auto_20210612_2324'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PracticeModel',
        ),
    ]
